-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 16:58:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ExercicisSQL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExercicisSQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExercicisSQL` DEFAULT CHARACTER SET utf8 ;
USE `ExercicisSQL` ;

-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Suppliers` (
  `id_Suppliers` INT NOT NULL AUTO_INCREMENT,
  `Suppliers_name` VARCHAR(45) NOT NULL,
  `Suppliers_address_street` VARCHAR(100) NOT NULL,
  `Suppliers_address_number` INT(3) NOT NULL,
  `Suppliers_address_floor` INT(3) NOT NULL,
  `Suppliers_address_door` VARCHAR(10) NOT NULL,
  `Suppliers_address_city` VARCHAR(45) NOT NULL,
  `Suppliers_post_code` INT(10) NOT NULL,
  `Suppliers_country` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_Suppliers`),
  INDEX `Name` (`Suppliers_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Brands` (
  `id_Brands` INT NOT NULL AUTO_INCREMENT,
  `Brands_name` VARCHAR(45) NOT NULL,
  `Suppliers_id_Suppliers` INT NOT NULL,
  PRIMARY KEY (`id_Brands`, `Suppliers_id_Suppliers`),
  INDEX `fk_Brand_Suppliers1_idx` (`Suppliers_id_Suppliers` ASC),
  CONSTRAINT `fk_Brand_Suppliers1`
    FOREIGN KEY (`Suppliers_id_Suppliers`)
    REFERENCES `ExercicisSQL`.`Suppliers` (`id_Suppliers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Glasses` (
  `id_Glasses` INT NOT NULL AUTO_INCREMENT,
  `Glasses_right_diopter` FLOAT NOT NULL,
  `Glasses_left_diopter` FLOAT NOT NULL,
  `Glasses_frame_type` VARCHAR(45) NOT NULL,
  `Glasses_frame_colour` VARCHAR(45) NOT NULL,
  `Glasses_right_glass_colour` VARCHAR(45) NOT NULL,
  `Glasses_left_glass_colour` VARCHAR(45) NOT NULL,
  `Glasses_price` VARCHAR(45) NOT NULL,
  `Brands_id_Brand` INT NOT NULL,
  PRIMARY KEY (`id_Glasses`, `Brands_id_Brand`),
  INDEX `fk_Glasses_Brand1_idx` (`Brands_id_Brand` ASC),
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brands_id_Brand`)
    REFERENCES `ExercicisSQL`.`Brands` (`id_Brands`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Customers` (
  `id_Customers` INT NOT NULL AUTO_INCREMENT,
  `Customers_name` VARCHAR(45) NOT NULL,
  `Customers_surname` VARCHAR(100) NOT NULL,
  `Customers_address` VARCHAR(100) NOT NULL,
  `Customers_telephone` INT(9) NOT NULL,
  `Customers_email` VARCHAR(100) NOT NULL,
  `Customer_registration_date` DATE NOT NULL,
  `Customers_recommended_by` INT(4) NULL,
  PRIMARY KEY (`id_Customers`),
  INDEX `Name` (`Customers_name` ASC),
  UNIQUE INDEX `Customers_email_UNIQUE` (`Customers_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Employers` (
  `id_Employers` INT NOT NULL AUTO_INCREMENT,
  `Employers_name` VARCHAR(45) BINARY NULL,
  `Employers_surname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Employers`),
  INDEX `Name` (`Employers_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExercicisSQL`.`Customers_buy_glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExercicisSQL`.`Customers_buy_glasses` (
  `id_Customers_buy_glasses` INT NOT NULL AUTO_INCREMENT,
  `Customers_id_Customers` INT NOT NULL,
  `Glasses_id_Glasses` INT NOT NULL,
  `Employers_id_Employers` INT NOT NULL,
  PRIMARY KEY (`id_Customers_buy_glasses`, `Customers_id_Customers`, `Glasses_id_Glasses`, `Employers_id_Employers`),
  INDEX `fk_Customers_buy_glasses_Customers1_idx` (`Customers_id_Customers` ASC),
  INDEX `fk_Customers_buy_glasses_Glasses1_idx` (`Glasses_id_Glasses` ASC),
  INDEX `fk_Customers_buy_glasses_Employers1_idx` (`Employers_id_Employers` ASC),
  CONSTRAINT `fk_Customers_buy_glasses_Customers1`
    FOREIGN KEY (`Customers_id_Customers`)
    REFERENCES `ExercicisSQL`.`Customers` (`id_Customers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Customers_buy_glasses_Glasses1`
    FOREIGN KEY (`Glasses_id_Glasses`)
    REFERENCES `ExercicisSQL`.`Glasses` (`id_Glasses`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Customers_buy_glasses_Employers1`
    FOREIGN KEY (`Employers_id_Employers`)
    REFERENCES `ExercicisSQL`.`Employers` (`id_Employers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
